select * from customer limit 50    -- Limit 50 means only 50 rows----

------------------------QUESTIONS--------------------------
--Q1: What is the total revenue generated by the male vs female?

select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q2: which customer used a discount but still spent more than average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


--Q3: Which are the top 5 products with highest average rating?

select item_purchased, round (avg(review_rating :: numeric),2) as avg_product_rating  -- agar hume decimal kam krne h to 
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5

--Q4: Compare the average purchase amount between standard and express shipping

select shipping_type, Round (avg(purchase_amount::numeric),2) as avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5: Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers

select subscription_status, 
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc


--Q6: Which product has highest % of purchase with discount applied?

select item_purchased,
 100 * sum(case when discount_applied='Yes' THEN 1 ELSE 0 end)/ COUNT(*)  as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


--Q7: segment customer into new,Returning, and loyal based on their total number of previous purchase ,and show the count of each segement

with customer_type as(          --Iska kaam hai temporary table banana, jise hum neeche wali query me use kar sakte hain.
select customer_id,previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 And 10 then 'Returning'
else'Loyal' 
end as customer_segment
from customer
)
select customer_segment, count(*) as total_customer
from customer_type
group by customer_segment


--Q8: what are the top 3 most puchase product with in each catergory

with item_count as(
select category,item_purchased,
count(customer_id)as total_orders,
row_number() over(partition by category order by count (customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_count
where item_rank<=3

--Q9: are customers who are repeat buyers(more than 5 previous purchase) also likely to sub?

select subscription_status,
count(customer_id) as Repeat_customer
from customer
where previous_purchases >5
group by subscription_status


--Q11 what is the revenue contribution of age group

select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue desc




--Q10 what is the revenue contribution of each category

select category,
sum(purchase_amount) as revenue
from customer
group by category



